added keynote speaker- alolita sharma
pythonindia/inpycon2021 pull request #15
Opened 2021-05-19 12:42 UTC by anistark

This is the full bio btw:

Alolita is a Principal Technologist at Amazon Web Services (AWS) where she leads open source observability and development on OpenTelemetry, Prometheus, Cortex, Grafana focused on metrics and log based observability. Alolita also serves as a member of the OpenTelemetry Governance Committee and as a board director of the Unicode Consortium. She contributes to open standards on Unicode Technical Committees and W3C. She has served on the boards of the OSI and SFLC.in. Alolita has led engineering teams at Wikipedia, Twitter, PayPal and IBM. Two decades of doing open source continue to inspire her. You can find her on Twitter @alolita.

Don't suppose we can accommodate this entire thing on website. Probably can link to blog post?

2021-05-19 13:23 UTC, SaptakS commented
Yeah. I think it is a better decision to link to the blog announcement for the keynote speaker.

2021-05-19 13:39 UTC, SaptakS requested changes
Left some comments related to the image. Also, updated the code for adding a link to blog. Please rebase on the main branch and then update the link attribute in keynote_speakers.yml

2021-05-19 14:00 UTC, anistark commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
So, we need to edit the image in that format with borders?
@noblebatman can you help with this?

2021-05-19 14:29 UTC, SaptakS commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
This is the link to the bordered image: https://github.com/pythonindia/inpycon2021/blob/main/static/images/s1.png. Would prefer the dimensions to be similar so everything lookssame as the main design.

2021-05-19 17:34 UTC, noblebatman commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
@anistark I actually have the SVG assets for those borders 
please check this out and let me know if this is not what you are looking for.
https://drive.google.com/drive/folders/1-SvzdGtubj7xNdxNzJkGqpY_Mv0ogMa-?usp=sharing

2021-05-19 17:40 UTC, noblebatman commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
@anistark or I believe this could be useful. 
https://drive.google.com/file/d/1xaMIVYogpvKR99R08yJUu9o92ELQAUV5/view?usp=sharing

2021-05-19 19:52 UTC, noblebatman commented
The Keynote Speaker announcement poster for Alolita Sharma, pfa
![AlolitaSharma](https://user-images.githubusercontent.com/20441340/118875523-c5d75580-b909-11eb-9e30-1c494c6615d1.png)

2021-05-20 02:40 UTC, anistark commented
> The Keynote Speaker announcement poster for Alolita Sharma, pfa
> ![AlolitaSharma](https://user-images.githubusercontent.com/20441340/118875523-c5d75580-b909-11eb-9e30-1c494c6615d1.png)

@rayandas For promotional content. ^

2021-05-20 02:41 UTC, anistark commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
@SaptakS should we use svg or png ?
And should we upload it on this repo ? Replacing `s1.png` ?

2021-05-20 06:34 UTC, sayanchowdhury commented
I've deleted the last two comment. The spelling of "Amazon Web Services" was misspelt. @noblebatman can you fix them and post again.

/cc @rayandas

2021-05-20 06:45 UTC, alolita commented
Thanks @sayanchowdhury for fixing the full form for the organization :-) Look forward to joining in!

2021-05-20 08:35 UTC, SaptakS commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
Any file format is fine. And yes you will need to upload it in the repo, replacing s1.png

2021-05-20 10:57 UTC, anistark commented on data/keynote_speakers.yml
> +    image: https://commons.wikimedia.org/wiki/File:Alolita_Sharma_004_-_Berlin_2011.jpg
@noblebatman Please upload to this repo the edited image by name s1.png inside images dir.

2021-05-20 11:08 UTC, sayanchowdhury approved these changes

2021-05-20 11:15 UTC, merged

2021-05-21 07:07 UTC, sayanchowdhury commented
@alolita Excited for your keynote. Apologies for the issue with the poster. We have published the blog and announced on Twitter

Blog: https://in.pycon.org/blog/2021/keynote-announcement-alolita-sharma.html
Twitter: https://twitter.com/pyconindia/status/1395366758454685696