Add the faq page
pythonindia/inpycon2021 pull request #31
Opened 2021-07-16 17:16 UTC by Sc0rpi0n101

CC: @raukadah @palnabarun @sayanchowdhury

2021-07-17 12:02 UTC, anistark approved these changes

2021-07-17 13:36 UTC, anistark commented on content/faq.md
> +You can submit your talk/workshop proposal on our [CFP Page](https://in.pycon.org/cfp/2020/proposals/). The deadline for submitting CFP for thsi year's conference has passed, please submit a talk nex
https://in.pycon.org/cfp/2021/proposals/

2021-07-17 13:37 UTC, anistark requested changes
Please fix the link. 2020 -> 2021

2021-07-18 02:51 UTC, raukadah approved these changes

2021-07-18 02:53 UTC, merged

2021-07-20 20:18 UTC, vipulgupta2048 reviewed
@Sc0rpi0n101 @raukadah Adding FAQ suggestions here, 
1. One about In-kind sponsors, I think we should highlight that here. (Question: How do I support the event?)
2. Pre-events and events leading up to the conference. Get the hype going, don't add anything specific just mention where the news will be (Twitter and mailing list) 
3. The combo ticket mention should list the exclusivity of combo tickets and a discount that we offer with them. 
4. Last FAQ be like: Still not convinced? Or got more questions? 
Answer: Watch the last year's conference (Youtube link) Or reach out to us on Zulip for any other queries. 
5. How is PyCon India being organized online? (People new to us may have doubts and we have a good answer. Give them the PPG to read and get more people wow'ed)

@Sc0rpi0n101 There are several spelling mistakes, pointed some out as after the PR is merged I can't add suggestions. 

- chek out the instructions
- tranfer your ticket(s) to someone else.
- submitting CFP for thsi year’s conference

Please run the content atleast aleast once through any grammar checker that you like.

2021-07-23 12:10 UTC, vipulgupta2048 commented
Closing https://github.com/pythonindia/inpycon2021-tasks/issues/69